apiVersion: apps/v1
kind: Deployment
metadata:
  name: archive-node-{{ .Values.archive.nodeName }}
  labels:
    app: archive-node-{{ .Values.archive.nodeName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: archive-node-{{ .Values.archive.nodeName }}
  template:
    metadata:
      labels:
        app: archive-node-{{ .Values.archive.nodeName }}
        testnet: {{ $.Values.testnetName }}
        role: archive-node
        version: {{ trunc 6 (split ":" $.Values.coda.image)._1 }}
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '10000'
        prometheus.io/path: '/metrics'
    spec:
      containers:
      - name: coda
        resources:
          limits:
          requests:
            memory: 14.0Gi
            cpu: 2.0
        image: {{ $.Values.coda.image }}
        command: ["/usr/bin/dumb-init", "/root/init_coda.sh"]
        args: [ "daemon",
          "-log-level", {{ $.Values.coda.logLevel }},
          "-log-json",
          {{- if $.Values.coda.logReceivedBlocks }}
          "-log-received-blocks", "true",
          {{- end -}}
          {{- if $.Values.coda.logSnarkWorkGossip }}
          "-log-snark-work-gossip", "true",
          {{- end -}}
          {{- range $.Values.coda.seedPeers }}
          "-peer", {{ . | quote }},
          {{- end -}}
          "-config-directory", "/root/.coda-config",
          "-client-port", "$(DAEMON_CLIENT_PORT)",
          "-rest-port", "$(DAEMON_REST_PORT)",
          "-insecure-rest-server",
          "-external-port", "$(DAEMON_EXTERNAL_PORT)",
          "-metrics-port", "$(DAEMON_METRICS_PORT)",
          "-archive-address", "$(DAEMON_ARCHIVE_PORT)",
          {{- if (ne $.Values.coda.runtimeConfig "") -}}
          "-config-file", "/config/daemon.json",
          "-generate-genesis-proof", "true",
          {{- end -}}
        ]
        env:
        - name: DAEMON_REST_PORT
          value: {{ .Values.coda.ports.graphql | quote }}
        - name: DAEMON_ARCHIVE_PORT
          value: {{ .Values.archive.ports.server | quote }}
        - name: DAEMON_CLIENT_PORT
          value: {{ .Values.coda.ports.p2p | quote }}
        - name: DAEMON_METRICS_PORT
          value: {{ .Values.coda.ports.metrics | quote }}
        - name: DAEMON_EXTERNAL_PORT
          value: {{ .Values.coda.ports.external | quote }}
        ports:
        - name: p2p-port
          protocol: TCP 
          containerPort: {{ .Values.coda.ports.p2p }}
        - name: graphql-port
          protocol: TCP 
          containerPort: {{ .Values.coda.ports.graphql }}
        - name: metrics-port
          protocol: TCP 
          containerPort: {{ .Values.coda.ports.metrics }}
        - name: external-port
          protocol: TCP 
          containerPort: {{ .Values.coda.ports.external }}
          hostPort: {{ .Values.coda.ports.external }}
        imagePullPolicy: Always
        volumeMounts: 
        - name: config-dir
          mountPath: /root/.coda-config
        {{- if (ne $.Values.coda.runtimeConfig "") }}
        - name: daemon-config
          mountPath: "/config/"
        {{- end }}
      # Archive Process
      - name: archive
        image: {{ $.Values.archive.image }}
        command: ["bash", "-c"]
        args: [ "coda-archive -postgres-uri {{ tpl .Values.archive.postgresUri . }} -server-port {{ .Values.archive.ports.server }}" ]
        env:
        imagePullPolicy: Always
        ports:
        - name: archive-server-port
          protocol: TCP
          containerPort: {{ .Values.archive.ports.server }}
        - name: archive-postgres-port
          protocol: TCP
          containerPort: {{ .Values.archive.ports.postgres }}
      volumes:
      - name: config-dir
        emptyDir: {}
      {{- if (ne $.Values.coda.runtimeConfig "") }}
      - name: daemon-config
        configMap:
          name: archive-daemon-config
      {{- end }}
